### ISSUE TITLE
Compatibility with other Sound Mods Question

### ISSUE THREAD

**Issue by ardissaps** [mattymatty97/audio_priority#1]
- [Charmonium](https://modrinth.com/mod/charmonium)
- [Presence of the Footstep](https://modrinth.com/mod/presence-footsteps)
- [OST Overhaul](https://modrinth.com/mod/ost-overhaul)
- [ExtraSound](https://modrinth.com/mod/extrasounds)

**Comment by mattymatty97** [comment]
for what i can see from a quick check on the code of the listed mods there should not be incompatibilities.

did you find any?

**Comment by ardissaps** [comment]
Cant test as no version is tagged 1.18.2, I install tru launcher

**Comment by mattymatty97** [comment]
first of all thanks @ardissaps for pointing me to this mods, except for [OST Overhaul](https://modrinth.com/mod/ost-overhaul) to which i don't really have a use, i'm loving all of them

about your question, i confirm all of them work out of the box with the latest version of my mod.
I still suggest to play a bit with the priority, threshold and instant values, mainly the ones from [ExtraSound](https://modrinth.com/mod/extrasounds), as that mod has to play sounds in the GUI so it might need some categories to be allowed to play in the MainMenu too ( instant Categories ) or to be played even if the sound poll if starting to fill up

**Comment by ardissaps** [comment]
I am not using [OST Overhaul](https://modrinth.com/mod/ost-overhaul) anymore as the music feel like out of place. I will do test again.
