### ISSUE TITLE
audio engine tweaks for some reason because "sound" is null

### ISSUE THREAD

**Issue by loti1234** [mattymatty97/audio_priority#10]
[crash-2023-10-01_21.21.42-client.txt](https://github.com/mattymatty97/audio_priority/files/12778043/crash-2023-10-01_21.21.42-client.txt)

**Comment by mattymatty97** [comment]
uh... weird... but easy fix

**Comment by mattymatty97** [comment]
a new hotfix toghether with a 1.20.2 version of the mod has been uploaded to the sites
