### ISSUE TITLE
Extra Sound Compatibility

### ISSUE THREAD

**Issue by ardissaps** [mattymatty97/audio_priority#3]
The sound after installing the mod sound from [ExtraSound](https://modrinth.com/mod/extrasounds) missing, like when i take anvil or amethyst block, sound when wearing armor etc also missing.

**Comment by mattymatty97** [comment]
By Default Unknwown/new Sound Categories ( like the ones that ExtraSound adds ) are set with lowest priority and threshold value of 0 ( effectively disabling them )
you can edit this value from ModMenu

**Comment by mattymatty97** [comment]
apparently there was a bug in the GUI that was crashing when loading the Options menu if there were additional categories
it's been fixed in version 1.1

**Comment by ardissaps** [comment]
Is the vanilla behavior have limit how many sound can trigger in a time? If yes, is it possible to just let every sound trigger using this mod?

**Comment by mattymatty97** [comment]
for what we know the sound pool limit is defined by the audio drivers of the computer and not by the game itself, so there is no way for us to remove the limit w/o causing crashes.

i'll have to try in the future to merge multiple sounds together but there is no guarantee that would work nor that it would still sound normal
