### ISSUE TITLE
ModMenu Config not working

### ISSUE THREAD

**Issue by tajemniktv** [mattymatty97/audio_priority#4]
Hi, I'm having some issues with setting up the mod. The config from ModMenu is not working (there's even no button). Saw an error in logs so I'm posting it. 
Full log: https://mclo.gs/wttPfrH
Error: https://mclo.gs/wTZnZow

Cheers

**Comment by mattymatty97** [comment]
weird, i'll try to investigate the problem later today, meanwhile you can manually edit the values in the audio_priority.json if you really need to tweak something

**Comment by tajemniktv** [comment]
I appreciate your quick response!
I also have a question regarding config of the mod. I would like to configure it, so it works with ExtraSounds mod, but I have no clue what to add and what to edit

Cheers!

**Comment by mattymatty97** [comment]
> Hi, I'm having some issues with setting up the mod. The config from ModMenu is not working (there's even no button). Saw an error in logs so I'm posting it. Full log: https://mclo.gs/wttPfrH Error: https://mclo.gs/wTZnZow
> 
> Cheers

Apparently i was using an outdated API for ModMenu that got deprecated with the change to 1.19.

version 1.2.1 (6cc7c110943d7929e92452e4695c516189da46e2) of the mod fixed the issue

**Comment by mattymatty97** [comment]
> I appreciate your quick response! I also have a question regarding config of the mod. I would like to configure it, so it works with ExtraSounds mod, but I have no clue what to add and what to edit
> 
> Cheers!

this mod should work out of the box with ExtraSounds, while the default values might not be the optimal for the mod itself:

ExtraSounds adds few sound categories which by default get a threshold of 10% ( meaning that if the sound pool is more than 10% full the sounds won't play ), lowest priority ( meaning all the other sounds will try to fill the sound pool first ) and no instantPlay permissions ( meaning sounds will only play while connected to a world and with the game not paused)

Suggestions for optimal settings:
All sound categories that are supposed to be played in the GUI need to have:
- InstantPlay permission ( be in the InstantCategory list )
- either High threshold values or high priority ( both is good too )

All sound categories that you want to always hear need to have:
- either High threshold values or high priority ( typically high priority is enough )

All sound categories that are ambient/background should have:
- either low threshold values or low priority ( typically low threshold is enough )

Threshold are the percentage at which the sound pool starts discarding sounds from that category

Priority helps ordering the sounds try to be played for each tick, they are sorted by priority and inside of the same priority by distance from the player ( lowest values have higher priority )

InstantPlay permission:
sounds in Minecraft can either be scheduled to play in a specific tick or be played immediately bypassing the priority queue.
normally only GUI and Menu sounds should be allowed to do so, as if all the sounds jump the priority the sound pool will get overloaded easily.
if a sound category does not have this permission wont play in the main menu or in the pause menu of single-player worlds

**Comment by tajemniktv** [comment]
Hi, so uhm I tried editing some values and then this happened: 
![image](https://user-images.githubusercontent.com/12156943/177065947-0aea0c0a-0377-4f6a-8286-c58256598278.png)

**Comment by mattymatty97** [comment]
Ok that's just me apparently having a stroke when i coded the menu :D
litterally 1 word to be changed

version 1.2.2 fixed it

i'll soon try to find someone to help me redesign the GUI
