### ISSUE TITLE
Backport to 1.16.5

### ISSUE THREAD

**Issue by B055-Man** [mattymatty97/audio_priority#5]
I still play on 1.16.5 as some mods I use have not been ported to 1.19 yet. I often get these errors and would appreciate it if you could backport this mod to 1.16.5. I fully understand that backporting is not a priority and fully understand if you are unwilling to help me.

**Comment by mattymatty97** [comment]
the problem with backporting ( or changing version in general ) is that it breaks all the GUI that allows users to tweak the mod.
W/o the GUI the mod can be compiled for basically any version.

that's also why i'm searching for help to redesign the GUI

**Comment by mattymatty97** [comment]
if you don't need the GUI i can compile you a version that will work in 1.16. otherwise it's gonna take a lot of time to recode

**Comment by B055-Man** [comment]
Thank you, I would really appreciate if you could compile me a version for 1.16. I'm sure I will be able to generate a config file from 1.19 or manually adjust the values in the config file.

**Comment by mattymatty97** [comment]
ok, hope this works for you:

[Github Release for 1.16.x](https://github.com/mattymatty97/audio_priority/releases/tag/backport)

**Comment by B055-Man** [comment]
Thanks very much!

**Comment by B055-Man** [comment]
Upon launching the game I recieve the following log 
`PolyMC version: 1.3.1-d7fad4bd


Launched instance in online mode

authserver.mojang.com resolves to:
    []

session.minecraft.net resolves to:
    []

textures.minecraft.net resolves to:
    [}

api.mojang.com resolves to:
    []


Minecraft folder is:
C:/Users/Larry/AppData/Roaming/PolyMC/instances/Fabulously.Optimized.MC.1.16.5.auto-update/.minecraft


Java path is:
D:/Documents/graalvm-ee-java8-21.3.2/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_331, using amd64 architecture, from Oracle Corporation.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/Larry/AppData/Roaming/PolyMC/instances/Fabulously.Optimized.MC.1.16.5.auto-update/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Larry/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] advancementinfo-1.16.5-fabric0.30.0-1.2
  [✔️] antighost-1.16.5-fabric0.30.0-1.1.3
  [✔️] architectury-1.32.66
  [✔️] audio_engine_tweaks-1.2.3-1.16-tmp
  [✔️] borderless-mining-1.0.6+1.16.2
  [✔️] byg-1.3.5
  [✔️] capes-1.1.2
  [✔️] cem-0.1.2
  [✔️] cloth-api-1.6.59
  [✔️] cloth-config-fabric-4.14.64
  [✔️] colormatic-2.2.9+mc.1.16.5
  [✔️] custom-fog-1.5.1
  [✔️] dynamic-fps-2.0.2
  [❌] entity-distance-1.0.4.jar (disabled)
  [✔️] EntityCulling-Fabric-1.3.0
  [✔️] fabric-api-0.42.0+1.16
  [✔️] fabric-language-kotlin-1.7.0+kotlin.1.6.0
  [✔️] fabrishot-1.4.0
  [✔️] fallingleaves-1.6.0+1.16.5
  [✔️] FallingTree-1.16.5-2.11.5
  [✔️] fastbench-2.3
  [✔️] fastfurnace-2.4
  [✔️] fastopenlinksandfolders-1.1.0
  [✔️] fatxporbs-0.0.9+1.16.4
  [✔️] ferritecore-2.1.0-fabric
  [✔️] hydrogen-fabric-mc1.16.5-0.2
  [✔️] illuminations-1.4.4
  [✔️] indium-1.0.0+mc1.16.5
  [✔️] iris-mc1.16.5-1.2.0-pre
  [✔️] item-model-fix-1.0.3+1.16
  [✔️] lambdabettergrass-fabric-1.0.3+1.16
  [✔️] lambdynamiclights-fabric-1.3.4+1.16
  [✔️] lazydfu-0.1.2
  [✔️] lithium-fabric-mc1.16.5-0.6.6
  [✔️] modmenu-1.16.23
  [✔️] no-potion-offset-1.0.2
  [✔️] NoChatLagForge-1.1.0-1.17-1.18
  [✔️] nofade-1.16.5-1.0.1
  [✔️] notenoughcrashes-4.1.4+1.16.5-fabric
  [✔️] phosphor-fabric-mc1.16.2-0.8.0
  [✔️] reeses_sodium_options-mc1.16.5-1.4.0
  [✔️] RoughlyEnoughItems-5.12.385
  [✔️] seamless-loading-screen-1.3.4+1.16.2
  [✔️] slight-gui-modifications-1.7.1
  [✔️] smoothboot-fabric-1.16.5-1.6.0
  [✔️] sodium-extra-mc1.16.5-0.4.0
  [✔️] sodium-fabric-mc1.16.5-0.2.0+build.4
  [✔️] tooltipfix-1.0.2-1.16
  [✔️] vanguard-uninstaller
  [✔️] WaveyCapes-fabric-1.2.0-mc1.16.5
  [✔️] WI-Zoom-1.3-MC1.16.5
  [✔️] yosbr-0.1.1

Params:
  --username  --version 1.16.5 --gameDir C:/Users/Larry/AppData/Roaming/PolyMC/instances/Fabulously.Optimized.MC.1.16.5.auto-update/.minecraft --assetsDir C:/Users/Larry/AppData/Roaming/PolyMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-server, -XX:+UseG1GC, -XX:+ParallelRefProcEnabled, -XX:MaxGCPauseMillis=200, -XX:+UnlockExperimentalVMOptions, -XX:+UnlockDiagnosticVMOptions, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -XX:G1NewSizePercent=30, -XX:G1MaxNewSizePercent=40, -XX:G1HeapRegionSize=8M, -XX:G1ReservePercent=20, -XX:G1HeapWastePercent=5, -XX:G1MixedGCCountTarget=4, -XX:InitiatingHeapOccupancyPercent=15, -XX:G1MixedGCLiveThresholdPercent=90, -XX:G1RSetUpdatingPauseTimePercent=5, -XX:SurvivorRatio=32, -Dsun.rmi.dgc.server.gcInterval=2147483646, -XX:+PerfDisableSharedMem, -XX:MaxTenuringThreshold=1, -XX:+EnableJVMCI, -XX:+UseJVMCICompiler, -XX:+EagerJVMCI, -XX:+UseStringDeduplication, -XX:+UseFastUnorderedTimeStamps, -XX:+UseAES, -XX:+UseAESIntrinsics, -XX:AllocatePrefetchStyle=1, -XX:+UseLoopPredicate, -XX:+RangeCheckElimination, -XX:+EliminateLocks, -XX:+DoEscapeAnalysis, -XX:+UseCodeCacheFlushing, -XX:+UseFastJNIAccessors, -XX:+OptimizeStringConcat, -XX:+UseCompressedOops, -XX:+UseThreadPriorities, -XX:+OmitStackTraceInFastThrow, -XX:+TrustFinalNonStaticFields, -XX:ThreadPriorityPolicy=1, -XX:+UseInlineCaches, -XX:+RewriteBytecodes, -XX:+RewriteFrequentPairs, -XX:+UseNUMA, -XX:-DontCompileHugeMethods, -XX:+UseFPUForSpilling, -XX:+UseNewLongLShift, -XX:+UseXMMForArrayCopy, -XX:+UseXmmI2D, -XX:+UseXmmI2F, -XX:+UseXmmLoadAndClearUpper, -XX:+UseXmmRegToRegMoveAll, -Dfile.encoding=UTF-8, -Djdk.nio.maxCachedBufferSize=262144, -Dgraal.TuneInlinerExploration=1, -Dgraal.CompilerConfiguration=enterprise, -Dgraal.UsePriorityInlining=true, -Dgraal.Vectorization=true, -Dgraal.OptDuplication=true, -Dgraal.DetectInvertedLoopsAsCounted=true, -Dgraal.LoopInversion=true, -Dgraal.VectorizeHashes=true, -Dgraal.EnterprisePartialUnroll=true, -Dgraal.VectorizeSIMD=true, -Dgraal.StripMineNonCountedLoops=true, -Dgraal.SpeculativeGuardMovement=true, -Dgraal.InfeasiblePathCorrelation=true, -XX:+UseLargePages, -XX:LargePageSizeInBytes=2m, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 6928


[16:47:38] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.16.5 with Fabric Loader 0.13.3
[16:47:41] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.13.3
[16:47:41] [main/INFO]: Dependencies overridden for fabric, antighost, advancementinfo, hydrogen, colormatic
[16:47:41] [main/INFO]: Loading 132 mods:
	- advancementinfo 1.16.5-fabric0.30.0-1.2
	- antighost 1.16.5-fabric0.30.0-1.1.3
	- architectury 1.32.66
	- artifice 0.14.6+1.16.5 via slight-gui-modifications
	- audio_engine_tweaks 1.2.3
	- autoconfig1u 3.2.2 via capes
	- borderlessmining 1.0.6+1.16.2
	- byg 1.3.5
	- capes 1.1.2
	- cem 0.1.2
	- cloth-api 1.6.59
	- cloth-armor-api-v1 1.6.59 via cloth-api
	- cloth-basic-math 0.6.1 via cloth-config2
	- cloth-client-events-v0 1.6.59 via cloth-api
	- cloth-common-events-v1 1.6.59 via cloth-api
	- cloth-config2 4.14.64
	- cloth-datagen-api-v1 1.6.59 via cloth-api
	- cloth-durability-bar-api-v1 1.6.59 via cloth-api
	- cloth-dynamic-registry-api-v1 1.6.59 via cloth-api
	- cloth-scissors-api-v1 1.6.59 via cloth-api
	- cloth-utils-v1 1.6.59 via cloth-api
	- colormatic 2.2.9+mc.1.16.5
	- com_electronwill_night-config_core 3.6.2 via byg
	- com_electronwill_night-config_toml 3.6.2 via byg
	- com_moandjiezana_toml_toml4j 0.7.2 via custom-fog
	- cotton-client-commands 1.0.1+1.16-rc1 via antighost
	- crowdin-translate 1.2 via antighost
	- custom-fog 1.5.1
	- dynamicfps 2.0.2
	- entityculling 1.3.0
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d via fabric
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d via fabric
	- fabric-biome-api-v1 3.1.13+3cc0f0907d via fabric
	- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d via fabric
	- fabric-command-api-v1 1.1.3+3cc0f0907d via fabric
	- fabric-commands-v0 0.2.3+3cc0f0907d via fabric
	- fabric-containers-v0 0.1.12+3cc0f0907d via fabric
	- fabric-content-registries-v0 0.2.5+3cc0f0907d via fabric
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d via fabric
	- fabric-dimensions-v1 2.0.8+3cc0f0907d via fabric
	- fabric-entity-events-v1 1.2.4+3cc0f0907d via fabric
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d via fabric
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d via fabric
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d via fabric
	- fabric-item-api-v1 1.2.2+3cc0f0907d via fabric
	- fabric-item-groups-v0 0.3.1+3cc0f0907d via fabric
	- fabric-key-binding-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-keybindings-v0 0.2.2+3cc0f0907d via fabric
	- fabric-language-kotlin 1.7.0+kotlin.1.6.0
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d via fabric
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d via fabric
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d via fabric
	- fabric-models-v0 0.3.1+3cc0f0907d via fabric
	- fabric-networking-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d via fabric
	- fabric-networking-v0 0.3.3+3cc0f0907d via fabric
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d via fabric
	- fabric-object-builders-v0 0.7.3+3cc0f0907d via fabric
	- fabric-particles-v1 0.2.5+3cc0f0907d via fabric
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d via fabric
	- fabric-renderer-api-v1 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-indigo 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-registries-v1 2.3.1+3cc0f0907d via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d via fabric
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d via fabric
	- fabric-rendering-v0 1.1.3+3cc0f0907d via fabric
	- fabric-rendering-v1 1.6.1+3cc0f0907d via fabric
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via fabric
	- fabric-screen-api-v1 1.0.1+3cc0f0907d via fabric
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d via fabric
	- fabric-structure-api-v1 1.1.12+3cc0f0907d via fabric
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d via fabric
	- fabric-textures-v0 1.0.7+3cc0f0907d via fabric
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d via fabric
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d via fabric
	- fabricloader 0.13.3
	- fabrishot 1.4.0
	- fallingleaves 1.6.0+1.16.5
	- fallingtree 2.11.5
	- fastbench 2.3
	- fastfurnace 2.4
	- fastopenlinksandfolders 1.1.0
	- fatxporbs 0.0.9
	- ferritecore 2.1.0
	- hydrogen 0.2
	- illuminations 1.4.4
	- indium 1.0.0+mc1.16.5
	- iris 1.2.0-pre
	- itemmodelfix 1.0.3+1.16
	- java 8
	- lambdabettergrass 1.0.3+1.16
	- lambdynlights 1.3.4+1.16
	- lazydfu 0.1.2
	- lithium 0.6.6
	- minecraft 1.16.5
	- mm 2.1 via slight-gui-modifications
	- modmenu 1.16.23
	- no-potion-offset ${version}
	- nofade 1.16.5-1.0.1
	- notenoughcrashes 4.1.4+1.16.5
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_codehaus_groovy_groovy 3.0.3 via slight-gui-modifications
	- org_codehaus_groovy_groovy-jsr223 3.0.3 via slight-gui-modifications
	- org_jetbrains_kotlin_kotlin-reflect 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_slf4j_slf4j-api 1.7.12 via iris
	- phosphor 0.8.0
	- reeses-sodium-options 1.4.0
	- roughlyenoughitems 5.12.385
	- roughlyenoughitems-api 5.12.385 via roughlyenoughitems
	- roughlyenoughitems-default-plugin 5.12.385 via roughlyenoughitems
	- roughlyenoughitems-runtime 5.12.385 via roughlyenoughitems
	- seamless_loading_screen 1.3.4
	- slight-gui-modifications 1.7.1
	- smoothboot 1.16.5-1.6.0
	- sodium 0.2.0+build.4
	- sodium-extra 0.4.0
	- spruceui 2.0.4+1.16 via lambdabettergrass
	- tooltipfix 1.0.2-1.16
	- vanguard 1.0.5 via illuminations
	- waveycapes 1.2.0
	- wi_zoom 1.3-MC1.16.5
	- yosbr 0.1.1
[16:47:45] [main/WARN]: Mod `no-potion-offset` (${version}) does not respect SemVer - comparison support is limited.
[16:47:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Larry/AppData/Roaming/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
Jul 16, 2022 4:47:46 PM org.multimc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: java.lang.RuntimeException: Error creating Mixin config audio_priority.mixins.json for mod audio_engine_tweaks
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 9 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config audio_priority.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 12 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_16 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.2 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 15 more`

**Comment by B055-Man** [comment]
Tested without other mods and recieved the same error. 

Edit: This issue was fixed by changing  "compatibilityLevel": "JAVA_16", to  "compatibilityLevel": "JAVA_8", in audio_priority.mixins.json.

**Comment by B055-Man** [comment]
Now upon launching the mod I recieve the following log https://mclo.gs/Vk20pnh

**Comment by mattymatty97** [comment]
mod requires java 16

**Comment by mattymatty97** [comment]
can you run your mc with java16 or later? you have polyMc so it should not be a problem

**Comment by B055-Man** [comment]
It doesn't let me run 1.16.5 with anything other than java 8

**Comment by mattymatty97** [comment]
aigh, imma recompile for java_8

**Comment by mattymatty97** [comment]
ok check again:
[Github Release for 1.16.x](https://github.com/mattymatty97/audio_priority/releases/tag/backport)

**Comment by B055-Man** [comment]
The game loads and this appears to work! Thanks very much.
