### ISSUE TITLE
C2ME incompatibility causes items to occasionally disappear after being thrown onto the sky

### ISSUE THREAD

**Issue by NaiNonTH** [mattymatty97/audio_priority#6]
I'm not going to say much here because I already have said about them here:
https://github.com/RelativityMC/C2ME-fabric/issues/166

**Comment by mattymatty97** [comment]
that is weird, i have only two mixins in this mod that only change how sounds are scheduled. i guess i'll have to contact c2me devs to check 👀

**Comment by NaiNonTH** [comment]
Same here. It seems like these 2 mods are unrelatable with each other until I found out. Took me quite a while to find it incompatible with C2ME though.

**Comment by NaiNonTH** [comment]
I'll close this issue for now, as you couldn't replicate the issue, Audio Engine Tweaks' code doesn't seem to interfere with C2ME's, and the problem is unknowingly fixed, as of now.
