### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [mattymatty97/audio_priority#7]
Do you plan on adding support for 1.19.3?

**Comment by mattymatty97** [comment]
i havent tested it, but the 1.19 version should work on 1.19.3 too

**Comment by Aces-and-Jacks** [comment]
going to the mod menu config crashes the game

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/7PvOZVG

**Comment by R00tB33rMan** [comment]
For the client, Audio Engine Tweaks works relatively well. Currently, the only real issue I'm having is crashes when opening the mod's settings category/UI.

**Comment by mattymatty97** [comment]
uh, by the error message it seems they changed one of the methods i use in the menu page. i'll try check the code as soon as i have time. in the meantime if you need to tweak the values you can use the settings file `audio_engine.json` in the config directory

**Comment by R00tB33rMan** [comment]
The most recent development build posted via the GitHub Releases section fully resolves its UI issues and is fully 1.19.3 compatible. Appreciate you fixing this! This issue can now be closed.

**Comment by mattymatty97** [comment]
nice to see that it properly worked, thanks for your feedback

**Comment by MicrocontrollersDev** [comment]
Will we get a Modrinth release for the new update?
Edit: Thanks!
