### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by BlueJayofEvil** [mattymatty97/audio_priority#9]
Just curious if there are any plans for 1.20 support.
Thanks in advance.

**Comment by mattymatty97** [comment]
yes i'm working on the 1.20.x port and should be able to publish it today

**Comment by mattymatty97** [comment]
i'm working on the 1.20 port and i hope to be able to publish it during the next week

**Comment by drakray** [comment]
any ETA on 1.20.1?
I use ~~too~~ many mods, and the default sound engine keep crashing, I hoped you mod could maybe fix that :D

**Comment by mattymatty97** [comment]
sadly my job has took priority over maintaining mods and the port will be delayed by at least one more month, i'm sorry bout that

**Comment by mattymatty97** [comment]
> any ETA on 1.20.1? I use ~too~ many mods, and the default sound engine keep crashing, I hoped you mod could maybe fix that :D
@drakray

if the audio engine straight up crashes i doubt my mod would help... 
if instead it "mutes" while spamming in the logs `Maximum sound pool size 247 reached` then my mod potentially might help by prioritizing which sounds have to be played and which ones can be discarded once the queue is full

**Comment by drakray** [comment]
Yeah no problem with that, real life always come first ;)

ok I understand. still, might help in the future if I still have this bug when you're ready ^_^
Thank you for your work :D

**Comment by mattymatty97** [comment]
i finally found the time to update to 1.20.1.
and as i was there i improved the detection of the duplicated sounds.. now you'll have even cleaner sound pools than before :smile:
https://github.com/mattymatty97/audio_priority/releases/tag/1.2.3-MC1.20.1
